# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d293841f60453b642634631612e240cc45589b0d4e19ab6a71459a06e90ad3ef6136edd75a52cc3cc8b1440ede1d6ca48941ff9499c122972d6cef4c291d59c3

test:
  secret_key_base: fa99a7207818745a89051e8ce5a3395436f9ad20b4ec9edd515ec2ef486ace0b2018e7b78712d25e11944f102d85ea25752c158fd95917b0c9ea8a3533e381a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
